-- Your SQL goes here
CREATE TABLE sessions (
  id SERIAL PRIMARY KEY,
  uid INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  token TEXT NOT NULL,
  active BOOL NOT NULL DEFAULT true,
  created TIMESTAMP NOT NULL,
  updated TIMESTAMP NOT NULL
);
