[package]
name = "main"
version = "0.1.0"
authors = ["dan@debassociates.com"]

[dependencies]
env_logger = "0.5"
serde = "1.0"
serde_json = "1.0"
serde_derive = "1.0"
juniper = "0.11.1"
juniper_rocket = "0.2.0"
rocket = "0.4.0"
diesel = { version = "1.0.0", features = ["postgres"] }
dotenv = "0.9.0"

[dependencies.rocket_contrib]
version = "0.4.0"
default-features = false
features = ["diesel_postgres_pool"]
