-- Your SQL goes here
CREATE TABLE deals (
  id SERIAL PRIMARY KEY,
  buyer_id INTEGER REFERENCES users(id) ON DELETE SET NULL,
  seller_id INTEGER REFERENCES users(id) ON DELETE SET NULL,
  house_id INTEGER REFERENCES houses(id) ON DELETE SET NULL,
  access_code VARCHAR(255) NOT NULL,
  status VARCHAR(255) NOT NULL,
  created TIMESTAMP NOT NULL,
  updated TIMESTAMP NOT NULL
);
