-- Your SQL goes here
CREATE TABLE deals (
  id SERIAL PRIMARY KEY,
  bid INTEGER REFERENCES users(id) ON DELETE SET NULL,
  sid INTEGER REFERENCES users(id) ON DELETE SET NULL,
  hid INTEGER REFERENCES houses(id) ON DELETE SET NULL,
  access_code VARCHAR(255) NOT NULL,
  status VARCHAR(255) NOT NULL,
  created TIMESTAMP NOT NULL,
  updated TIMESTAMP NOT NULL
);
